package com.siscopi.beans.negocio;
// Generated 7/11/2017 12:29:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CatMenus generated by hbm2java
 */
public class CatMenus  implements java.io.Serializable {


     private Integer idCategoria;
     private String nombre;
     private String niveles;
     private Integer nivelPadre;
     private boolean visible;
     private String img;
     private Set<RolesMenus> rolesMenuses = new HashSet<RolesMenus>(0);

    public CatMenus() {
    }

	
    public CatMenus(String nombre, boolean visible) {
        this.nombre = nombre;
        this.visible = visible;
    }
    public CatMenus(String nombre, String niveles, Integer nivelPadre, boolean visible, String img, Set<RolesMenus> rolesMenuses) {
       this.nombre = nombre;
       this.niveles = niveles;
       this.nivelPadre = nivelPadre;
       this.visible = visible;
       this.img = img;
       this.rolesMenuses = rolesMenuses;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNiveles() {
        return this.niveles;
    }
    
    public void setNiveles(String niveles) {
        this.niveles = niveles;
    }
    public Integer getNivelPadre() {
        return this.nivelPadre;
    }
    
    public void setNivelPadre(Integer nivelPadre) {
        this.nivelPadre = nivelPadre;
    }
    public boolean isVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public Set<RolesMenus> getRolesMenuses() {
        return this.rolesMenuses;
    }
    
    public void setRolesMenuses(Set<RolesMenus> rolesMenuses) {
        this.rolesMenuses = rolesMenuses;
    }




}


