package com.siscopi.beans.negocio;
// Generated 7/11/2017 12:29:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CatRoles generated by hbm2java
 */
public class CatRoles  implements java.io.Serializable {


     private Integer idRol;
     private String rol;
     private Set<RolesUsuarios> rolesUsuarioses = new HashSet<RolesUsuarios>(0);
     private Set<RolesMenus> rolesMenuses = new HashSet<RolesMenus>(0);

    public CatRoles() {
    }

	
    public CatRoles(String rol) {
        this.rol = rol;
    }
    public CatRoles(String rol, Set<RolesUsuarios> rolesUsuarioses, Set<RolesMenus> rolesMenuses) {
       this.rol = rol;
       this.rolesUsuarioses = rolesUsuarioses;
       this.rolesMenuses = rolesMenuses;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set<RolesUsuarios> getRolesUsuarioses() {
        return this.rolesUsuarioses;
    }
    
    public void setRolesUsuarioses(Set<RolesUsuarios> rolesUsuarioses) {
        this.rolesUsuarioses = rolesUsuarioses;
    }
    public Set<RolesMenus> getRolesMenuses() {
        return this.rolesMenuses;
    }
    
    public void setRolesMenuses(Set<RolesMenus> rolesMenuses) {
        this.rolesMenuses = rolesMenuses;
    }




}


