package com.siscopi.beans.negocio;
// Generated 7/11/2017 12:29:29 PM by Hibernate Tools 4.3.1



/**
 * RolesMenus generated by hbm2java
 */
public class RolesMenus  implements java.io.Serializable {


     private Integer idRolmenu;
     private CatMenus catMenus;
     private CatRoles catRoles;

    public RolesMenus() {
    }

    public RolesMenus(CatMenus catMenus, CatRoles catRoles) {
       this.catMenus = catMenus;
       this.catRoles = catRoles;
    }
   
    public Integer getIdRolmenu() {
        return this.idRolmenu;
    }
    
    public void setIdRolmenu(Integer idRolmenu) {
        this.idRolmenu = idRolmenu;
    }
    public CatMenus getCatMenus() {
        return this.catMenus;
    }
    
    public void setCatMenus(CatMenus catMenus) {
        this.catMenus = catMenus;
    }
    public CatRoles getCatRoles() {
        return this.catRoles;
    }
    
    public void setCatRoles(CatRoles catRoles) {
        this.catRoles = catRoles;
    }




}


